### ISSUE TITLE
when there is no training at all, i think it would be the best to raise Error

### ISSUE THREAD

**Issue by maxmarketit** [automl/Auto-PyTorch#63] opened 2020-06-29 15:19 UTC
During training, I somehow end up with these messages,

```
00:12:08 Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method Process pynisher function call:
```

And most of the time, I get nothing from training for 5 min, 10 mins, even days.

So i guess i would be better to raise Error and stop the training if the problem is not solvable by autoPyTorch.

**Comment by ravinkohli** [comment] 2021-05-20 14:07
Hey, thanks for this question. Actually, we have been working on a new version of autopytorch that is available on the branch [`development](https://github.com/automl/Auto-PyTorch/tree/development), for docs, see [this](https://automl.github.io/Auto-PyTorch/development/).  Now we feel it's ready for people to test their workflows with this version. 

So I suggest you try out your data with the development version. For an example on how to use the API, find it [here](https://automl.github.io/Auto-PyTorch/development/examples/index.html)

Feel free to ask any questions about the implementation here. And if you feel the issue is resolved, kindly close it.

**Closed** 2021-06-24 20:52 UTC
