### ISSUE TITLE
Discrepancy of first layer in AutoNetClassification and corresponding get_pytorch_model()

### ISSUE THREAD

**Issue by ZepengHuo** [automl/Auto-PyTorch#70] opened 2020-11-13 17:09 UTC
I trained a small dataset with AutoNetClassification method, and feed the data with 79 features. However when I called get_pytorch_model() the return architecture gives me 78 neurons in the first layer. So the same dataset can't be fed into the pytorch model

**Comment by ZepengHuo** [comment] 2020-11-13 17:18
I suspect it's the truncated_svd preprocessing? But whenever I switch to other techniques, it tells me I need to put a larger max_runtime which i also tried

**Comment by LMZimmer** [comment] 2020-11-30 09:33
Indeed preprocessing will change the dimensionality of the data, that could be via truncated SVD or also omitting a column of there are NaN values in it. Could you perhaps specify your setup or give a minimal example?

**Comment by ravinkohli** [comment] 2021-05-20 13:57
Hey, thanks for this question. Actually, we have been working on a new version of autopytorch that is available on the branch [`development](https://github.com/automl/Auto-PyTorch/tree/development), for docs, see [this](https://automl.github.io/Auto-PyTorch/development/).  Now we feel it's ready for people to test their workflows with this version. 

So I suggest you to try out your data with the development version. For an example on how to use the API, find it [here](https://automl.github.io/Auto-PyTorch/development/examples/index.html).

Specifically to resolve your issue, I suggest you feed the data to the fitted pipeline instead of the pytorch model. I think that would give the best results. 
Feel free to ask any questions about the implementation here. And if you feel the issue is resolved, kindly close it.

**Closed** 2021-05-21 17:29 UTC
